=== JoelProjects/apps/jhong-wun/question_set.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT question-set (description?, time, question*)>
<!ELEMENT question (subject, choices*, answer)>
<!ELEMENT choices (choice*)>

<!ELEMENT description (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT choice (#PCDATA)>
<!ELEMENT answer (#PCDATA)>

=== JoelProjects/apps/jhong-wun/question_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question-set SYSTEM "question_set.dtd">
<question-set>
	<description>慈濟夏令營2005</description>
	<time>30</time>
	<question>
		<subject>中秋節吃</subject>
		<choices>
			<choice>餃子</choice>
			<choice>粽子</choice>
			<choice>月餅</choice>
		</choices>
		<answer>3</answer>
	</question>
	<question>
		<subject>划龍舟是在</subject>
		<choices>
			<choice>中秋節</choice>
			<choice>端午節</choice>
			<choice>春節</choice>
		</choices>
		<answer>2</answer>
	</question>
	<question>
		<subject>畫蛇添</subject>
		<choices>
			<choice>豬</choice>
			<choice>竹</choice>
			<choice>足</choice>
		</choices>
		<answer>3</answer>
	</question>
	<question>
		<subject>青梅竹</subject>
		<choices>
			<choice>馬</choice>
			<choice>罵</choice>
			<choice>驢</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>走馬看</subject>
		<choices>
			<choice>花</choice>
			<choice>畫</choice>
			<choice>華</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>這圖_很美麗</subject>
		<choices>
			<choice>書</choice>
			<choice>畫</choice>
			<choice>花</choice>
		</choices>
		<answer>2</answer>
	</question>
	<question>
		<subject>我好_福</subject>
		<choices>
			<choice>辛</choice>
			<choice>幸</choice>
			<choice>性</choice>
		</choices>
		<answer>2</answer>
	</question>
	<question>
		<subject>小明說他_胡</subject>
		<choices>
			<choice>姓</choice>
			<choice>性</choice>
			<choice>幸</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>電_幫大家很多忙</subject>
		<choices>
			<choice>惱</choice>
			<choice>鬧</choice>
			<choice>腦</choice>
		</choices>
		<answer>3</answer>
	</question>
	<question>
		<subject>這_筆很特別</subject>
		<choices>
			<choice>枝</choice>
			<choice>支</choice>
			<choice>至</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>弟弟很_皮</subject>
		<choices>
			<choice>跳</choice>
			<choice>調</choice>
			<choice>挑</choice>
		</choices>
		<answer>2</answer>
	</question>
	<question>
		<subject>_天我去游泳</subject>
		<choices>
			<choice>昨</choice>
			<choice>坐</choice>
			<choice>做</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>我不喜歡_試</subject>
		<choices>
			<choice>考</choice>
			<choice>靠</choice>
			<choice>烤</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>(林)宇環</subject>
		<choices>
			<choice>ㄌㄧㄣˊ</choice>
			<choice>ㄌㄧˊ</choice>
			<choice>ㄌㄧㄥˊ</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>李品(融)</subject>
		<choices>
			<choice>ㄖ ㄨㄥˊ </choice>
			<choice>ㄖ ㄨㄥ</choice>
			<choice>ㄏㄨㄥˊ</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>鄧立_</subject>
		<choices>
			<choice>語</choice>
			<choice>嚴</choice>
			<choice>言</choice>
		</choices>
		<answer>3</answer>
	</question>
	<question>
		<subject>黃莨(喻)</subject>
		<choices>
			<choice>ㄩˊ </choice>
			<choice>ㄩˇ</choice>
			<choice>ㄩˋ</choice>
		</choices>
		<answer>3</answer>
	</question>
	<question>
		<subject>百家姓裡趙錢孫</subject>
		<choices>
			<choice>李</choice>
			<choice>黃</choice>
			<choice>陳</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>陳(珮)瑜</subject>
		<choices>
			<choice>ㄆㄟˋ</choice>
			<choice>ㄆㄟˇ</choice>
			<choice>ㄅㄟˇ</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>張麥(可)</subject>
		<choices>
			<choice>ㄎㄜˇ</choice>
			<choice>ㄎㄜˋ</choice>
			<choice>ㄍㄜ</choice>
		</choices>
		<answer>1</answer>
	</question>
	<question>
		<subject>春節是農曆什麼時候?</subject>
		<choices>
			<choice>1月1日</choice>
			<choice>8月15日</choice>
			<choice>5月5日</choice>
			<choice>3月3日</choice>
		</choices>
		<answer>1</answer>
	</question>	
	<question>
		<subject>春節要吃什麼?</subject>
		<choices>
			<choice>年糕</choice>
			<choice>月餅</choice>
			<choice>粽子</choice>
			<choice>柚子</choice>
		</choices>
		<answer>1</answer>
	</question>	
	<question>
		<subject>過年的前一夜叫什麼?</subject>
		<choices>
			<choice>大年夜</choice>
			<choice>守歲</choice>
			<choice>除夕夜</choice>
			<choice>以上皆是</choice>
		</choices>
		<answer>4</answer>
	</question>		
	<question>
		<subject>除夕夜,全家吃什麼飯?</subject>
		<choices>
			<choice>團圓飯</choice>
			<choice>年夜飯</choice>
			<choice>圍爐</choice>
			<choice>以上皆是</choice>
		</choices>
		<answer>4</answer>
	</question>	
	<question>
		<subject>正月15日是什麼節?</subject>
		<choices>
			<choice>上元節</choice>
			<choice>元宵節</choice>
			<choice>下元節</choice>
			<choice>以上皆非</choice>
		</choices>
		<answer>2</answer>
	</question>	
</question-set>
